# Generated by Django 4.2.30 on 2026-04-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_id', models.CharField(max_length=100, unique=True)),
                ('content_type', models.CharField(default='service', max_length=50)),
                ('item_index', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('features', models.JSONField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Services Content',
                'verbose_name_plural': 'Services Contents',
                'ordering': ['item_index', 'created_at'],
            },
        ),
    ]
