# Generated by Django 4.2.30 on 2026-04-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(choices=[('hero', 'Hero'), ('stat', 'Stat'), ('feature', 'Feature'), ('cta', 'CTA'), ('testimonial', 'Testimonial')], max_length=50)),
                ('item_index', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Home Content',
                'verbose_name_plural': 'Home Contents',
                'ordering': ['item_index', 'created_at'],
            },
        ),
    ]
