# Generated by Django 4.2.30 on 2026-04-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='trust_badge',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='content_type',
            field=models.CharField(choices=[('hero', 'Hero'), ('stat', 'Stat')], max_length=50),
        ),
    ]
