# Generated by Django 4.2.30 on 2026-04-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homecontent_trust_badge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
