# Generated by Django 4.2.30 on 2026-04-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homecontent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon name for stat items (lucide-react icon names)', max_length=100, null=True),
        ),
    ]
