# Generated by Django 4.2.30 on 2026-04-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessContact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(default='contact', max_length=50)),
                ('item_index', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('office_hours', models.JSONField(blank=True, null=True)),
                ('google_maps_url', models.URLField(blank=True, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Business Contact',
                'verbose_name_plural': 'Business Contacts',
                'ordering': ['item_index'],
            },
        ),
    ]
