# Generated by Django 4.2.30 on 2026-04-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(choices=[('hero', 'Hero'), ('team_member', 'Team Member'), ('value', 'Value'), ('timeline_event', 'Timeline Event')], max_length=50)),
                ('item_index', models.IntegerField(default=0)),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('paragraphs', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('mission', models.TextField(blank=True, null=True)),
                ('vision', models.TextField(blank=True, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'About Content',
                'verbose_name_plural': 'About Contents',
                'ordering': ['item_index', 'created_at'],
            },
        ),
    ]
